CREATE TABLE POO_PESSOA (
        CPF VARCHAR2(11) PRIMARY KEY NOT NULL,
        NOME VARCHAR2(50) NOT NULL,
        DATANASC VARCHAR2(10) NOT NULL,
        ENDERECO VARCHAR2(50),
        BAIRRO VARCHAR2(30),
        CIDADE VARCHAR2(35),
        ESTADO VARCHAR2(20),
        CEP VARCHAR2(9),
        TELEFONE VARCHAR2(10),
        CELULAR VARCHAR2(11),
        SEXO VARCHAR2(9) NOT NULL,
        ESTADOCIVIL VARCHAR2(10),
        RG VARCHAR2(15),
        EMAIL VARCHAR2(50) NOT NULL,
        NUMERO NUMBER(8));
        
CREATE TABLE POO_ALUNO (
        CPF VARCHAR2(11) PRIMARY KEY NOT NULL,
        ESCOLARIDADE VARCHAR2(20) NOT NULL);

ALTER TABLE POO_ALUNO ADD CONSTRAINT FK_PESSOA_ALUNO FOREIGN KEY (CPF) REFERENCES POO_PESSOA(CPF);

CREATE TABLE POO_INSTRUTOR (
        CPF VARCHAR2(11) PRIMARY KEY NOT NULL,
        FORMACAO VARCHAR2(50) NOT NULL,
        AREAATUACAO VARCHAR2(50) NOT NULL);

ALTER TABLE POO_INSTRUTOR ADD CONSTRAINT FK_PESSOA_INSTRUTOR FOREIGN KEY (CPF) REFERENCES POO_PESSOA(CPF);

CREATE TABLE POO_CURSO (
        SIGLA VARCHAR2(10) PRIMARY KEY NOT NULL,
        NOME VARCHAR2(50) NOT NULL,
        CARGAHORARIA NUMBER(5) NOT NULL,
        VALOR NUMBER(8, 2) NOT NULL,
        DATAVIGENTE VARCHAR2(10),
        VALORHORAINSTRUTOR NUMBER(6,2),
        PROGRAMA VARCHAR2(140));

CREATE TABLE POO_TURMA (
        SIGLATURMA VARCHAR2(10) PRIMARY KEY NOT NULL,
        SIGLACURSO VARCHAR2(10) NOT NULL,
        NOME VARCHAR2(50) NOT NULL,
        DATAINICIO VARCHAR2(10),
        DATATERMINO VARCHAR2(10),
        PERIODO VARCHAR2(10) NOT NULL,
        OBSERVACOES VARCHAR2(140),
        QTDEVAGAS NUMBER(3) NOT NULL);
        
ALTER TABLE POO_TURMA ADD CONSTRAINT FK_CURSO_TURMA FOREIGN KEY (SIGLACURSO) REFERENCES POO_CURSO(SIGLA);